### ISSUE TITLE
High registers (r8+) cannot be used

### ISSUE THREAD

**Issue by mattlgy** [rust-console/gba#158]
A change to rustc, in how instruction_set and asm interact, broke some uses of higher registers. Example error:

```
error: invalid register `r8`: high registers (r8+) cannot be used in Thumb-1 code
   --> .../gba/src/sync/statics.rs:100:59
    |
100 |       out("r2") _, out("r3") _, out("r4") _, out("r5") _, out("r8") _,
    | 
```

See https://github.com/rust-console/gba/pull/157 for some more discussion.

**Comment by Lokathor** [comment]
Update since it's been however many months:

This code will still not compile:
```rust
fn foo(mut x: i32) -> i32 {
  unsafe { core::arch::asm!("", inout("r8") x) }
  x
}
```

However, this code with the `instruction_set` attribute will compile
```rust
#[instruction_set(arm::a32)]
fn foo(mut x: i32) -> i32 {
  unsafe { core::arch::asm!("", inout("r8") x) }
  x
}
```

Overall, this isn't something that the `gba` crate can fix, so I'm going to close the issue as "fixed enough".

If people still consider this a problem, they should file an issue with the compiler itself: https://github.com/rust-lang/rust/issues/
