### ISSUE TITLE
Can we get a breakdown of the logic in the whole `crt0.s` file?

### ISSUE THREAD

**Issue by Lokathor** [rust-console/gba#63]
Right now there's a little commenting, but it's still kinda mysterious.

I think it'd be a good segment to add to the end of the "GBA Assembly" lesson if we put the entire `crt0.s` file with a comment on every line and a breakdown of _why_ we're doing the different steps and stuff.

* [ ] We copy `.data` to IWRAM but not `.bss`, is this just a legacy thing because `.bss` wasn't used at first?
* [ ] Can we talk about what `gbafix` does exactly?
* [ ] GBATEK says that IRQ and BIOS uses the top 256 bytes of IWRAM, and I see the part that sets the IRQ stack pointer, but it's kinda fuzzy how those three ARM instructions are setting the pointers, because it looks like the second block (user stack) would just overwrite what got set during the first block (IRQ stack)
* [ ] How does that copy work? It looks like we're carefully setting things up and then calling `CpuSet`, correct? After that, the control flow just "falls through" into the next block and jumps to main, right?
* [ ] Can we cover the control flow between "power on" and when we hit here? Particularly how `swi 0` and `swi 1` will interact with what `crt0.s` defines.

And any other notes and explanations you think a beginner would need!

**Comment by ketsuban** [comment]
> We copy `.data` to IWRAM but not `.bss`, is this just a legacy thing because `.bss` wasn't used at first?

There's nothing to copy to `.bss` because `.bss` is the section for static variables without a defined initial state.

> Can we talk about what `gbafix` does exactly?

Sure; it writes a valid header to the beginning of the file.

> GBATEK says that IRQ and BIOS uses the top 256 bytes of IWRAM, and I see the part that sets the IRQ stack pointer, but it's kinda fuzzy how those three ARM instructions are setting the pointers, because it looks like the second block (user stack) would just overwrite what got set during the first block (IRQ stack)

The ARM7TDMI uses register banking, so there's a different register for the stack pointer in each operating mode. Each write to `sp` is preceded by setting the CPSR to put the CPU in a different mode.

> How does that copy work? It looks like we're carefully setting things up and then calling `CpuSet`, correct? After that, the control flow just "falls through" into the next block and jumps to main, right?

Yep. `CpuSet` takes three arguments:

* `r0` contains the source address;
* `r1` contains the destination address;
* `r2` contains a couple different things:
    * Bits 0 through 20 are the length of data being copied;
    * Bit 24 configures whether we're copying data or filling a region of memory with the value of `r0`;
    * Bit 26 gives the data size (0 for halfwords, 1 for words).

Here's some revised comments for stuff that is perhaps less obvious than it was when I was writing this routine.

```
    @ copy .data section to IWRAM
    ldr r0, =__data_lma     @ source address
    ldr r1, =__data_start   @ destination address
    ldr r3, =__data_end
    @ store length in bytes in r2
    sub r2, r3, r1
    beq .Lskip              @ don't try to copy an empty .data section
    @ turn length in bytes into length in words, rounded up
    add r2, #3
    mov r2, r2, asr #2
    @ set bit 26 to tell CpuSet we want to copy by words
    add r2, #0x04000000     @ copy by words
    @ call CpuSet BIOS function (* 0x10000 because we're in ARM mode)
    swi 0xb0000
```

(There's no actual reason to use `r3` here; you can replace it on lines 22 and 23 with `r2`. It's an artifact of my inexperience with ARM assembly at the time I put `crt0.s` together.)
