### ISSUE TITLE
See about moving to normal GCC binutils

### ISSUE THREAD

**Issue by Lokathor** [rust-console/gba#80]
Apparently we don't really need to specifically use devkitpro's ARM binutils, we can probably just use totally normal GCC binutils for `ARMv4TDMI`.

Currently we use devkitpro for the assembler and the linker.

We can't use LLVM's own linker because it has a v5 minimum because it uses the `BLX` instruction.

Still, it's worth it to give it a try using more a toolchain that's even more common than we're currently using.

**Comment by Lokathor** [comment]
note for later http://gnutoolchains.com/arm-eabi/

**Comment by Nitori-** [comment]
I'm using the assembler/linker/objcopy from Ubuntu's `binutils-arm-none-eabi` package without issue (at least for the red-green-blue dots example).

I'm still using devkitpro's gbafix but since I'm writing some small rust utils for other things (graphics conversion right now) I might just implement equivalent logic there as well so I can just avoid having to install devkitpro entirely.

**Comment by Lokathor** [comment]
Yeah, i also recall there being a rust crate that can work as a gbafix replacement, so we can maybe move 100% away from devkitPro if that's working.

I've been doing the hal stuff and othet crates lately but i should be done with that soon enough and be able to get to this particular problem as one of the first ones when I'm back to working on the gba crate itself

**Comment by Lokathor** [comment]
Completed in https://github.com/rust-console/gba/pull/106
