### ISSUE TITLE
.iwram section in linker.ld?

### ISSUE THREAD

**Issue by lifning** [rust-console/gba#91]
Some library code out there that's optimized due to being a performance hotspot (like TONC's memcpy32, https://github.com/devkitPro/libtonc/blob/master/asm/tonc_memcpy.s#L42 ) can opt to live in the .iwram section of the binary, presumably because otherwise the instruction fetch-execute cycle would be subject to the 5-8x slower timings for living in .text (in ROM), per https://problemkaputt.de/gbatek.htm#gbamemorymap

When I try to link a program with such a relocation in it using https://github.com/rust-console/gba/blob/master/linker.ld though, it fails to link because it doesn't have such a section.  So far my naive attempts to add a section by that name (without quite grokking the .ld file's language) have just produced invalid binaries, as have my attempts to use devkitARM's gba.specs / https://github.com/devkitPro/devkitarm-crtls/blob/master/gba_cart.ld in conjunction with this crate.  Any ideas?

**Comment by Lokathor** [comment]
This should be possible.

I'd have to review the exact syntax to get it working. I'll try to look into it on the weekend or something. You can ping me on the gbdev discord if you don't hear from me, because i might forget.

**Comment by Lokathor** [comment]
Okay so, my ISP actually died over the weekend so I've been a little out of sorts, but having a glance back at this issue I think that you'd want to set it up similar to how the devkit arm sets it up.

First: the quick and dirty path is to try just putting a [link_section attribute](https://doc.rust-lang.org/reference/abi.html#the-link_section-attribute) named `.data` onto a function and see if the function gets copied to `iwram` with the rest of the `data`. I honestly haven't gotten around to doing this before so I don't know if the attribute makes the function be marked `.data` and _also_ `.text` or if it makes it be marked `.data` _instead of_ `.text`. If it _replaces_ the `.text` tag with a `.data` tag then everything will work perfectly with the current script.

Second: if that doesn't work you have to do it "properly" instead:
* You need to "exclude" `iwram` entries from being processed in the main `text` section processing [line 90](https://github.com/devkitPro/devkitarm-crtls/blob/master/gba_cart.ld#L90)
* You need to add a new dedicated section for `iwram` handling which then puts in all the iwram entries with markers around them so that the assembly startup can do the copy of that info from the ROM into RAM. This will largely work the same as the general `data` section does, and arguably you could even just put the `iwram` entries into the `data` part of the script [line 160](https://github.com/devkitPro/devkitarm-crtls/blob/master/gba_cart.ld#L160)
* Finally you'd put attribute on the function and it should link to the right area. Of course you also need to adjust the boot assembly code to perform the iwram copy as well as the data copy.

I don't think I have too much time to investigate myself any time soon, so I'll let you try it out and report back.

**Comment by lifning** [comment]
I ended up adding things tagged `.iwram` to the existing `.data` section like so:
```c
    __data_lma = .;
    .data : {
        __data_start = ABSOLUTE(.);
        *(.data .data.*);
        *(.iwram .iwram.*);
        . = ALIGN(4);
        __data_end = ABSOLUTE(.);
    } >iwram AT>rom = 0xff
```
which seems to work for `#[link_section=".iwram"]` in rust, but when i call code from tonclib that's relocated to .iwram, the program resets altogether, i presume because of exception vector shenanigans.  i'll keep fiddling with it to see if that's some mistake at link time or something.

(while i was there, also trivially added an ewram section for some larger r/w static structures, and added it to the boot code - which i also switched to FastCopy 'cause i didn't see a reason not to)
```c
    __ewram_lma = .;
    .ewram : {
        __ewram_start = ABSOLUTE(.);
        *(.ewram .ewram.*);
        . = ALIGN(4);
        __ewram_end = ABSOLUTE(.);
    } >ewram AT>rom = 0xff
```
```asm
    @ copy .ewram section to EWRAM
    ldr r0, =__ewram_lma     @ source address
    ldr r1, =__ewram_start   @ destination address
    ldr r2, =__ewram_end
    subs r2, r1             @ length
    @ these instructions are only executed if r2 is nonzero
    @ (i.e. don't bother copying an empty .ewram section)
    addne r2, #3
    asrne r2, #2
    swine 0xc0000
```
